# 异常

异常是指程序在运行过程中的非正常情况。

当程序违反Java编程语言的语义约束时，Java虚拟机会将此错误作为异常信号发送给程序。eg：数组下标越界

一些编程语言及其实现通过强制终止程序来对此类错误做出反应；还有一些编程语言允许实现以任意或不可预测的方式作出反应。这两种方法都不符合JavaSE的设计目标：提供可移植性和健壮性。

异常情况总是难免的，开发过程中要充分考虑各种意外情况，使程序有较强的容错能力。这叫做异常处理。

Java编程语言规定，当违反语义约束时，将抛出异常，并将程序从异常发生处转移到程序员可以指定的程序处理。

## 异常体系

Java语言中所有错误和异常都是`Throwable`类的实例或其子类表示，也只有中作为此类(或其一个子类)的实例的对象由`Java虚拟机`抛出，或者可以由`Java throw`语句抛出。只有这个类或其子类可以是`catch`字句中的参数类型。

`Throwable`又有两个子类，`Error`和`Exception`。

### Error

`Error`是`Throwable`的子类，表示严重的问题，合理的应用程序不应该试图捕获。一般不应该抛出(`throw`)这种类型的错误，由虚拟机抛出。普通程序通常不会从中恢复。

> 能处理，但是不建议处理

### Exception

`Exception`合理的应用程序想要捕获的条件，普通程序可能希望从中恢复的所有异常的超类(父类)。

分为两大类：运行时异常(`RuntimeException`)、编译(设计)时异常。

- 运行时异常(`RuntimeException`)：是在Java虚拟机的正常操作期间可以抛出的那些异常，程序运行期间抛出的异常。不要求必须处理，但是不处理程序就停止了。(==主==)
- 设计时异常：在程序未运行时的异常。

> unchecked exception 是指 运行时异常以及 Error==不强制处理的异常==
>
> checked exception 是指除 运行时异常以外的所有异常类别。也就是说，检查的异常类是Throwable及其所有子类。==强制处理的异常==

##### 常见异常：

- `java.lang.IndexOutOfBoundsException`下标越界异常，索引值不合法
  - `java.lang.ArrayIndexOutOfBoundsException`数组下标越界
  - `java.lang.StringIndexOutOfBoundsException`字符串下标越界
- `java.lang.NullPointerException`空指针异常，对 `null `进行了运算
- `java.util.InputMismatchException`输入不匹配异常
- `java.lang.ArithmeticException`算术异常 eg: `/zero`
- `java.lang.ClassCastException`类型转换异常
- `java.lang.NumberFormatException`数字格式化异常
- `java.lang.IllegalStateException`非法状态异常
- `java.lang.CloneNotSupportedException`不支持克隆操作异常，一般是被克隆的类未实现 `Cloneable` 接口导致

## 异常处理⭐

异常处理通过5个关键字来实现，`try`、`catch`、`finally `、`throw`、`throws`。

其中`try`、`catch`、`finally`是处理异常的，`throw`、`throws`抛出异常

### 捕获异常

##### 使用`try-catch`处理异常

- 将我们认为可能发生异常的代码放到`try`中

- 将可能产生的异常放到`catch`中

- 在`catch`中写处理此异常的代码

> - 如果程序的异常得到处理，程序会继续执行。如果没有处理程序会终止运行。
>
> - 一个`try`可以有多个`catch`语句，如果产生异常(对象)会一个一个按顺序比对，如果产生的异常是`catch`声明的异常就执行当前`catch`中的代码，其他`catch`不会被执行。执行完`catch`，如果方法中还有其他代码，则继续执行。多个`catch`中捕获的异常要从子类到父类，一般最后一个是`Exception`。
>
> - 如果一个`try`代码块中多个语句都有异常，当第一个异常被触发，`try`中的其他代码不会被执行。所以，`try`的范围要尽量小，尽量准确。
>
> - `catch`捕获到的是异常对象。

##### try-catch-finally

无论 try 语句中是否会发生异常，最后都会执行 finally 语句代码。

try/catch/finally 一个 try 可以有多个 catch 只能有一个 finally 。 try 可以单独和 finally 使用。

先执行try语句块/catch语句块(匹配到的)中return之前的语句，再执行finally语句块中的语句，最后执行try/catch块中的return语句。如果finally块中有return语句，直接返回，其它块中return失效

### 抛异常

##### throw

之前都是程序在运行过程中，由`jvm`抛出的异常。我们也可以主动抛异常，使用`throw`关键字。通过`throw`抛异常的对象。

如果方法中有`throw`关键字表示会抛异常，要在方法头使用`throws`关键字声明此方法有可能会抛出的异常，这样方法的调用者就要做异常的处理。`throws`可以声明多个异常，用`,`隔开。

- `throw`运行时异常(`RuntimeException`及其子类)，可以不在方法头使用 throws 声明此方法有可能抛出的异常
- `throw`的不是运行时异常，必须在方法头使用 `throws`声明此方法有可能抛出的异常

##### throws

`throws`关键字可以在方法头声明方法可能抛出的异常，这也是处理异常的一种方法。

- `throws`的是 unchecked 异常的话，调用处可以不处理

- `throws`的是 checked 异常的话，调用处必须处理

> 重写方法时要求抛出的异常相同或变小指，重写方法抛出的异常是父类方法异常类或其子类
>
> 构造方法可以使用 throws 关键字，但是如果父类构造`throws`的是检查异常（checked exception）子类构造也得`throws`，不能使用`try-catch`处理